[tools]
flux2 = "latest"
helm = "latest"
k9s = "latest"
opentofu = "latest"
sops = "latest"
terraform = "latest"

[tasks."oci-provision"]
description = "creates oci k8s free infrastructure"
dir = "tf"
run = """
if [ -d ".terraform" ]; then
    echo "Terraform is initialized."
else
    echo "Terraform is NOT initialized. Running init now..."
    terraform init
fi
if [ -f "variables-private.auto.tfvars" ]; then
    echo "Private variables files found"
else
    echo "Setup variables-private.auto.tfvars"
    exit 1
fi
terraform apply
"""

[tasks."k9s"]
description = "runs k9s with provisioned cluster config"
dir = "tf"
run = """
if [ -f ".kube.config" ]; then
    k9s --kubeconfig .kube.config
else
    echo ".kube.config file does not exist"
    exit 1
fi
"""

[tasks."setup-fluxcd"]
env.GITHUB_TOKEN = { required = "Github token required for fluxcd setup" }
env.GITHUB_USER  = { required = "Github username required for fluxcd setup" }
description = "Fluxcd configuration to reconcil this repo definitions from provisioned cluster"
run = """
flux bootstrap github \
  --owner=$GITHUB_USER \
  --repository=$(basename -s .git $(git config --get remote.origin.url)) \
  --branch=main \
  --path=./flux/cluster \
  --personal
"""