[tools]
flux2 = "latest"
helm = "latest"
opentofu = "latest"
sops = "latest"
terraform = "latest"

[tasks."oci-provision"]
description = "creates oci k8s free infrastructure"
dir = "tofu"
run = """
if [ -d ".terraform" ]; then
    echo "Terraform is initialized."
else
    echo "Terraform is NOT initialized. Running init now..."
    terraform init
fi
if [ -f "variables-private.auto.tfvars" ]; then
    echo "Private variables files found"
else
    echo "Setup variables-private.auto.tfvars"
    exit 1
fi
terraform apply -target null_resource.kube_config
"""
