apiVersion: v1
kind: Secret
metadata:
    name: wireguard-client
    namespace: default
type: Opaque
stringData:
    wg0.conf.template: ENC[AES256_GCM,data:UgbFfc3zEPWJHCMfb5nqoMQJBD2EmFW+JNrH5pB6JR53Sq5XxV3y72qK5a6vQP7nr4DdG/CgjCrd4gAdlo8jBs2XzMg/68HyoHuMOleqg8fYnu6ej1JlrmIy0yxl26zEERYJ3hv1UTgtJEMQXuQPH6GUnNoafznoTL9IL2fddlqGiX883TjaiBBga+XcXKj8XiDEKLexkhHSv+r1X42RhUFT3e1ngcMkSwqO+4x3UfAl5/28ALIv3+lelycfq+R+1blclaQ6hmTUbKG69cSsShOkwM2fqc1seIu9C/8jG+h+3Gnt0rSPBdWCu42DWUH6L4/piluKuWdoLHqi+HIu5PTSIf78cO8U5afwJJnpg7+7,iv:t+MJF7Y+Mv0aLnYdpq+J0ZZDLnbb0+8/AOwvWbkGCZk=,tag:5DGfbMTwHyzurYbVMKVPhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4em1LbGxlTW4yaTFFNGxn
            eDhYUVFXVWNNL3pwWHo4QXpZTERJOXdua0FFCmdHeEpvdHZVeEd5V0c0RzNoRXpn
            dFdBVW1FSVFqa1lZV21zSGRTQVpBL2MKLS0tIFV4bjJ1Z0NFVnY0MnlVcS81ZjV6
            MWxXZTZNRDZISHJDMlM2dUhDYTY2VHcKSt/E4Puz448dYQzoQEI7SxgICsnHxr0q
            z8cx11vWeGrYfMz4l/Ki6QkTQUcDesTBjUEmCr+CNIE+YMf9/fvQ1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T16:43:46Z"
    mac: ENC[AES256_GCM,data:HRtloBuDI+NOEuewlyfnf9fQwIrKeeAuitaJUcY+8ojtyaX9NmbaXR7p8RuNH0OBb1k25gwgkAPbs6PWsaQoLn5adi3Veit0OeG/tkKHHSkO4Cf5BZd1T0aVwCtb+WAH7VC+NWsd/VbZLmUprCdHSmGtc3oPTy7YF49CBrG+i+s=,iv:jUsvhrntsbuPDhRoXLzvo7PyYE7O06Og2aIm3sk3xn8=,tag:U+Q0NW8w3TmFJa9ZynnJVA==,type:str]
    version: 3.13.3
