apiVersion: v1
kind: Secret
metadata:
    name: wireguard-client
    namespace: default
type: Opaque
stringData:
    wg0.conf.template: ENC[AES256_GCM,data:CsnBxuSz6Q5wA8PrF0JtbzuzmTOfAd7Jp+IQj0jIFsDKtPZPXseUP/umS6pAi7JpK7uLP5m0PgBVj/ytowj8igzh0v/Kv8P6VeubYSl6U7mbclXraL19CHdPgN7KuvkQb/N1JOtHHyC3Df5Yfm5MbrwR0hUJyzW+fGVcdqi7k6LId0m40M0e35YzQTteXSRA8UA7FTi9R0EN6OJIoS69/rI+gEFr3OiQP3soLxpyNflWAgyk1MvZS6kgp132UynEqGGwvqbXHCImu0moNNlSDYsViLhPmCJpEfSxbXxhKCsKVU3f9mlktDo64clcMrNFwFAVnPBoLw5NGyQJWsJHcU5aK5iVxRkZRkwn9OmEcC+NzgicVZqYhTVBeQaxi0BcUP2CUSBvoOHAkCLVHOY=,iv:oCNBzTet3TbYGd5vc1VMMDlEye5CyKMJf6AhmEMGDvs=,tag:9BCkufY9ogUr9VbJqO5S+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S1JTMnMrK2doS0pMdW5F
            SEltMGl6dzk0SE5wd2ZRVGVKYnZlMXFPaUNzCkkrOHBNY0c2TXpYNTR2cFpkOEdk
            MnkxUFJkdHFnMnF0OUZsdjF5b2xmM2cKLS0tICswQitHME9xc241OXY3VWwrbDVR
            MEYrQ2oveVdMVkRsRkNrTlpOOExsK0UKZTZruTHmbyUR9+nDnaNp2E5KpwyoKRcj
            rSsyy4B3WRRtM0ainSlTeMYholNRgsjV7GiGhv3n6EN8xYI7Xex9UQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T11:43:42Z"
    mac: ENC[AES256_GCM,data:jHYfT5vsCN+QI/J9+ptd/Ar51jnibRQMwpbXVL1smU7pAAJQH3+kTmUOwwCQWtRrY9ju1yQ/m0H8lkBXyrPKskQvFUa3I/ReUMxvK4pN9iN/LLtiFSWpmPS0ycbRn4iZgw4Y1hSD5DipdiB/TS+pzF/7yUolSWYmPiu0oSAEHZY=,iv:35rYR332fQd9bCmAKFwn76uY8/uqg4CO6S6Iz6gMUeA=,tag:x7B0PTXfb7sPuQB0d/Dz/g==,type:str]
    version: 3.13.3
