apiVersion: v1
kind: Secret
metadata:
    name: wireguard
    namespace: default
type: Opaque
stringData:
    wg0.conf.template: ENC[AES256_GCM,data:eSdSB/l9CRzMzodePBzshvKOwBDM0WjvpBjQdPfuExVGs1T4RguV9wlKD7A1f01x3AVj/81S5piva2wGpS4pnqeVS7ulFsJv0F8btu08lFg9KvZ6f8wXduj0WW2329OA1J6v+fA5JYGV6XGIRAlhB68BULyqStdxGW0a8lh+jNrfHxY9GRl2f9OpndPHEE/oW8rjC7qbPt5lBAKu4bN5VnowMFpQ6AOUSHHiEq1k6k5PBbalnOvh0Eni59jkqmcMaNayrwToCZWubqueRMZgdeQj7jP+hvUWKA5G/phIM8iCY1OacUyevK5w/y1jjyUXHUaWH5ec3KKcslNLmvqUWPdSkzD6pvo1WfUsjmfNR3esF+TMfoPamWEE8KgAnsHvLMg54hTdpZ8UylYHBxGtGZ8dTO+LxYgLts6/dsa9qxkcM8KF+kAvykzA0352QzC3uc+C2phUwEJQU31t0ycsYDbnegF3AMhD6WyVbAck2hrjuJJfjCnLLFiefwhu3tM28JUeMxC4ahZWOqR4BO1FZgCJ2ukPTyGoDP3g7lv463HczNmFOQcOboKPyDRbXz1x+srX9jnSB0TMr69aWT3Pf78+lMy9oIRGHVFmS5OrwEbAe46Mvi0doDbMKTPtz/kKtWysmaDH7wt3qZjMhqBrESoMSH8G9yXoZsx74qlbiMbvmWETagFrDD2HPDRvRE3ro3/xWrYugcKCcPiGjo18ilPRAqBAUFIdaktP6/aZJguiUdFXognjDB8cNTpdr+QwZg13De4VtYelyA==,iv:RGljB63rCykZsWM0Y3IkCKuwK3BkU5H3y3hHmPqny60=,tag:O483jergdBlUFKb19oG9hA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWTRMcUJyVDR6T1p1cCtH
            alQ2eFNuczJ0OWxXcE0ybkhXSjdrV2lkVTBZCk9hb2NoQjVlWnlJd1FBRzVwNXBK
            NXZCQ2lyZHNUbld0U2VJUGt3WWZsOVEKLS0tIGZrN2JmaFZFb2dqUXRkdkRhQTB2
            d0x0eEw0RjNVa1pCdk9Cc1VtREhPZXMKJYBimJyRFTwbmSdMWXb7kW6X2LqdjMgD
            GDx13yZx16CY1Z+dJ9aLMn6MyYbHiqugx/7GEUHdbyM7Mvyd+zD7tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T11:40:09Z"
    mac: ENC[AES256_GCM,data:1TzG+H5z/eGyS9qyEWP3HyKwQp5Lf0/xNQM0Lsb003CV9Ql5xvx8EOhHzuLOOWMg0UM04TDo6t9jMsvzvBJZqF+vnMwgbPF94OhstpgF03ju/Sa9OaNj/vJqYwups9Km2RGERH20o1ZD46jJc16sfD0hjcD3fD9+U1oMhlj+QIE=,iv:XCgVBUKXHhKUrUxcBCJE+1e2TE6Yh38jwWt2Wfyo9nY=,tag:QDIW30AWYHdf8XZU5nLW6Q==,type:str]
    version: 3.13.3
