apiVersion: v1
kind: Secret
metadata:
    name: wireguard
    namespace: default
type: Opaque
stringData:
    wg0.conf.template: ENC[AES256_GCM,data:KwzEn2VC6Smw6mQEiabxAyD4O5Ah07NedynzVIx4PykpVPiCSeaEx76ml17dTYrU8J17mz+S37n6yiwo7/I+OxHYGYtLuPlLFSwcDunc20kcS7b99HgvADnQE6QRQPGqW6q3M+KRICV03FlMEzqJL8PTmEOwyh6QpYb/kVpAWUTXIgununj1JMDU03nkE9CHr7U3dXxWhVxCXJ4bXkYJpvVBaM0PudkoickQk6qC9l/wWfgWdt80EZkwH9N7CJNjboYEC2czGMwqkI1OzD47VwVhCUUrgL/jIRT1CiQ/1I4GBxcf6GonHCSD/2eSb4/KFnAyYkCDDQ4HRYBZ+UDegoV25+z3v4rp0rAz1Daqk92Nu3r22UhjFzYUoXy90UPXjZyGg//FVfo0GNt+K8WujVEhGdHvAeZbETBbeo/zNB3t7WspaiTitMXI2bJzW3ewEUwcYPWjPBP175ieS/ibm5tXmsxZGBLNqXfIW0nq3uva+FTq+HUbvkDWmyakwURro5dREkpxFQD6dawQnjqyluvbTJFBPtQVo6QOeTVRMuQlvnKs4KTOHXn2xXxZlGY/fVWss7DQfp2lM68Qjko1lIXYz9/UWpjjMHJ2bIjJqwJPMznYvFOL20vdRrK2ZivVSb/odEmAYwPtRIXhToSv7ubJZLR2S08xRYltD6HX/pV30Ly6NXDCF3XXpZu/a6UIzYv1z/W2gQnd2C1x0736VNNLzgTxnWUfUb3B/tyn/57FM2naUGAfRiil57aG0e+lONwfU5VRQajWfQ==,iv:Lozgb1YBpFzrZYzkC8U4OttVfhGzWy0ok8+A0y+ym+Q=,tag:4x6QVfvRxojE2MYa6jv23A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVk9TcFdialA3ckJwMTA3
            ZERIRXExOUJuMUpVS25kSVoxU0hqZVpodXdJCktPLzZUdFkvQ1doaWYzNnhQbm93
            SiswSUVlbkxRNWhIUE16TVl0eUxwOG8KLS0tIHpFdXlmZy9RYW54aE1jRmNzOWNI
            a3ZCcnh5cVVOd0liQ3VMRGpmczhXRXcKMDIDH34a4lKjNlRDpblAeQiHFNFd6Sxe
            v9+zcCG9KeNXiAiF0En6bJ/lbL133+Xt7aGum920kRgq0bCIErItLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T11:43:38Z"
    mac: ENC[AES256_GCM,data:7CBmF/LypJiGDEdo9sU98iMG0rOV+A6Chd75Td5C+yTN82+Y3iJJzOrB/gRHjMDuZ/4DZuzcBzvX9pABNyCA7lz0vMdwJPKM7QomLLhhYzS3V/X9l6Rfbvr3lrn/aVjaSAb2hkV+3N52CFbqfSzBKWBKs3hYq4jQl72Q5FNklqk=,iv:+1d+5/RnDjM6hhhAQaaVWReiARn5vCB8q5gzlnX5hH0=,tag:cAg4/6TJ/4B/hcxsRVQatg==,type:str]
    version: 3.13.3
