apiVersion: v1
kind: Secret
metadata:
    name: wireguard
    namespace: default
type: Opaque
stringData:
    wg0.conf.template: ENC[AES256_GCM,data:C2LB+v+HO2jsQvwkX75+idHgzhQuUyraoqU1o9wT8GOC1FWUTJwgrQaUDFRRojcAKU7a/9DXLnUI4n2m2u2KhGsHsCltxzxYNe3hU82343p0hnv0JOpnh6NEvetC1KFog4GB4LltzTy+M1nPg954sgEgk3mtqdSn5g+EQiggJBsR9fM+SoN5I4aAW74iM71FMHKu7MqUa+flFC+1G8yv25n25/dIjz6Z0PzHK9Kv1ivNZ4Oh2uSIEk8I5wcCz8/SWx22swJ3xq8GON02fr6oNkWP8sjbFgHQHjZEylhxvCCWSGWsrJaDOFgJP3UXrW40nuj6KakqbOP4dWQ9oUZd1JMKKNl7DE9gZjmXglNw56MMJVVzqzWbT32XS1oUrE/BzcOw4tSi6CUp1UYWkgjtyrEMJp+3W33BR8MUEa61qYkn77y7cgd746uKfH3rnF164yLF0l3Pu6j6H7qoCoQj7VJKOg30qIW1JLhxD/8KxHz4SV0FdmYEjrFTgrqVojZ3PAY+I9hwZBEo0yG8fZxE6pVghXfQI4udBaps7yQvbBUtBTmGdw58ASD+DkHMecXcCTCOe+TGQp1WgsujHDu7XxoZbC3XdmETJ2dKND6gpC3SX82vVijgShDINrWpBjfOcqtDrPsmvIjThw+NyOWcV82Vf2mLrQyxnYYKp9KY3g/oCrWVSI+IAGOGQombPKsvNOa+FPsidilwQ0JapkZ9gWBUOA/zr34JkcgY/5tBxPQGx2Hb1YZZN6aJWpmsByjEnql02AShUWk8ZQ==,iv:cBfyFg7g6wkThyewSaSkkebrht7ocuPuaCWX8tc8rd4=,tag:vtG0XW8V6myfKoMPjdnBlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVTZiYzJvTmsyQWphKzFl
            V1E2U2FtWXdmVWllZERSTUYwQ1JNMENSbUFNCllsNjZsR0h2MTQ3dnFPZEZEV1pu
            aWduWGNpMEdrclZHczY0cVB6S2k5eWsKLS0tIHkvcTN6WVo0ZUdTMWtic3FVZ0xh
            cmdpZVhwVVpjQ3o4SnpBQUhtYzJPY0UKg8WIJ6dqB4Co+BpPM92MkwZyjQjmi4Uh
            ayVKi1F7pAXsi8PxQtzPSgRIJV189elC6emWmZOhEMkjAEAsyoVIew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T14:33:08Z"
    mac: ENC[AES256_GCM,data:5TrqHN2z29weS2JuTLguf+l0K/AyKjFNSFOoiQJTdWVXIARgnrpaIveX7dKrhntGokk5lKUrrV0oViWLtAiRwN617nHAcbbzr3CdHuqenPx6a6kNzVZ/h+qMuHPHNcUKu8tLlAJBmWPYquo8CHbd8KttuSVohHn3GvNAKjaIU9c=,iv:rtHuOKCS4HDP5Mg+z5d0AsQSr4uu2wgpgsLA1cxhNiU=,tag:qmysV3dJe+cPKnrY+CehlQ==,type:str]
    version: 3.13.3
