- name: Create deploy user
  user:
    name: deploy
    groups: sudo
    shell: /bin/bash
    append: yes

- name: Add SSH key for deploy user
  authorized_key:
    user: deploy
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Disable root login and password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    # If line matched with regexp, it"s replaced with line, if not nothing is done
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
  notify: restart sshd