apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- provisioned/ingress/ingress-node-port.yaml
- provisioned/storage/storage-access.yaml
- nginx-1/static-nginx.yaml
- nginx-2/static-nginx.yaml