apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress-nginx-controller/helmrepository.yaml
- ingress-nginx-controller/helmrelease.yaml
- public-ingress.yaml
- internal-ingress.yaml
- provisioned/ingress/ingress-node-port.yaml
- provisioned/storage/storage-access.yaml
- nginx-1/static-nginx.yaml
- nginx-2/static-nginx.yaml
- wg/deployment.yaml
- wg/wg-config.yaml
- internal-dns/internal-core-dns.yaml
- cert-manager/helmrepository.yaml
- cert-manager/helmrelease.yaml
- cert-manager/issuer.yaml
- external-dns/helmrepository.yaml
- external-dns/helmrelease.yaml
- external-dns/secret.yaml