apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gateway
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /one
          pathType: Prefix
          backend:
            service:
              name: static-nginx-service-1
              port:
                number: 80
    - http:
        paths:
        - path: /two
          pathType: Prefix
          backend:
            service:
              name: static-nginx-service-2
              port:
                number: 80