apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:qYP4dkEpUzsRenNrnmmSpC7cO+VB+hmPYIIsiuauM5v3lO6jERJxxo5K//En19OR/FTD1IK8KWBoovcJRndgXcUThKh5aiSjm3qvLd308w==,iv:CAvH8AUMuWGnMva3ZQZs4gVW4Ldwid7EBehfb78UmpA=,tag:BJlkrAdhjgy/ZuXOkKKvSQ==,type:comment]
    #ENC[AES256_GCM,data:jxtVd/eyUetTWM8gOA0H6hIIyOxLX/Q=,iv:M3zjIYrnvObN8tand/uG0ExJOB1dpiURaQVGLGK3wuY=,tag:vhSmgcQdZTz9q4AyRKXtTQ==,type:comment]
    encryption-key: ENC[AES256_GCM,data:7HMX8VlFsOStlT4vRKKNb2lbZaEbbaUX3CUpNE/T6iMvE0k4YgjpXo+3fA04qATnNlG5dLolSmKpAjOVufeinQ==,iv:5lMqfv1Yqd7hhpqXr0mkldjWareTDz9ovB625x8A0yM=,tag:LXHQhANOLfdwx1V9yOCJPw==,type:str]
    instance-owner-email: ENC[AES256_GCM,data:P/FDNZI1+lliE0mofA==,iv:IuGb2vMPToh+W26iEZjfMLou77kS8Q7Jh5CeN5u/ctw=,tag:KCHVFmEsd38CjunbzVJ0SA==,type:str]
    instance-owner-first-name: ENC[AES256_GCM,data:jpzd,iv:3V0oNgiKaeOv1h6cGaWsaM9FUP+K7Udc4zX/GQlJX00=,tag:6PP1ILvXRlItRSYNWUw6oA==,type:str]
    instance-owner-last-name: ENC[AES256_GCM,data:qJ487/c=,iv:Brn78zQKnghrJHUERC8PsXo9oVakwHensl1+TcCluq4=,tag:30Lkk6wR330JBOzSqmCzYQ==,type:str]
    instance-owner-password-hash: ENC[AES256_GCM,data:0Ji4CitEGeGVSsLmbLfObKoOIX9dYth0vCHC59tv7IoGpsaAZRBS/tx/uUPPLW7/6DpQ1Y+fvvXtI8mH,iv:Smw4g8+LEOHgqhBLo7XjM+NY3FZZcq6OweZDDbY9je4=,tag:H0CN49Ax6PKKxcFHOVQTJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y3lGZ1RSMzBUOXQ4T2hu
            N29VTkdJbUswYmZNcjJhLzZRVXY2QVNrMFdnCngzQ2ZidWZYazIwOVE0aXh4N2VF
            ZE1KbHVubXF5QkZWOFRRODdCOWJMcFEKLS0tIGVYWHVSc1dRb2diNlJnQzJCb2xr
            OWZoWmZyMEdqdnA0V3ZuWWVOYzhYS0EK8TWf74ZZYrXXpXg1QNF/oHHc7B9vJSye
            BC5jXEPJhz1r9UFIxl0rgXDZB4vzzRNfCS/jrA+2HHjZz9/L5rRHjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T17:04:15Z"
    mac: ENC[AES256_GCM,data:ezkyeCIp8Zwxv2sZ2k4pziPrBtOQvebFe3XeVIODMGK09XdrBDWF9ccGF7WSrebrluI3hPBBm+9b7eCma5CRaYtjYDoyUtvGyykuia6ZfWYvwcU+HpqUQ1pGZw8kIM+FHOLZ5VIHy2Rv3+yN7WeKwhuJvQEynrqUtuS5NwCpjCA=,iv:WL9aSgfB4WRNRhg8btO7mUPa2bXsc3dgDi6gEbKPglo=,tag:z8dNX1RmOECvh8HQ8rso4g==,type:str]
    version: 3.13.3
