apiVersion: v1
kind: Secret
metadata:
    name: n8n-auth-creds
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wfTblxM=,iv:EAJTYM3ojNbsjIhXXhWFVW51lGGnCLKw0Vg3JjN4gFk=,tag:84M/VwOGksNIZpLTbYgjMA==,type:str]
    password: ENC[AES256_GCM,data:DMjjbnmo7xiLqx35dJJeEYgpgmB1cYqV,iv:6weNnI/NtpiQaxFFKeoRnICVd7JoSgLH25TAr9wuQDo=,tag:ksAIAjYojqv/4gaoLIHexQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1emJoUjZMancxMm1sUE9z
            RitYTk90Z1J6TGJZMDRwaUhzSWpDc012VWdzCnZ6Q0ZTSEw0bDlGTU82ZGdwRUhv
            Tm1RR1lPRlF6NWhtTXIyb0dldE9EdmMKLS0tIFFwajdyNjlCMndZMm9vRThyVUhD
            bFRtSmZHWnhlNGNFTDFyaHZyUmRJY2sKmwkamohjVwWUpDlHMdTDW1ebZjZ0UTm+
            nM46H5uA9U10mTTallBSrJk8W9JiRyL3+/sdDhl8V0vnAdBFgkbTzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T12:52:49Z"
    mac: ENC[AES256_GCM,data:T5lC4NSH/6qd4sJIiBwrWKPiJdgoR4ed2k5KgHSDj6BPvsDQ6LcoRzct+Ub6CBbuCuWNEyyRqqEroD/XTznuMcCMUj/k1N+LsrBgsF/nqdtebvrIlX7BlSl/vwDYcsQADYGTKXg1xcYR3zYzsk4g/5yn4vJWUXs3CWqqHHMnL1A=,iv:DajvIAwf0lEoirEk1TNVA3jfCFAbLyL6xXzP/ORgFc8=,tag:+YpZejvVuxnbW3zW0uHo6A==,type:str]
    version: 3.13.3
