apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:c2eq9QHpu6RtyK93lSh0E7+/A/P0ffCdAdtMUs6MUl3gMK7mPmfdu/a3ux4+rC2hpd3yJQTWz95WUuRtZFesK4kRJZnFjDA/xXhSWpq5LA==,iv:fK2V/PvYmBcSlV8Sq+ioUuJAWi0AkaJRws0B2abPBfs=,tag:19anRnoCQwJI7nligJvblg==,type:comment]
    #ENC[AES256_GCM,data:GNTQ6CVtA8tifcazZdDx/z6kXzTC2Uk=,iv:KH6rVuwuReFa5mLzYaKLHDKqSWbwie9xOrCWDQfN7CE=,tag:w+LyyBIhJ/QkC9vjSaspJg==,type:comment]
    encryption-key: ENC[AES256_GCM,data:ZG77s6ZLa89Jp0WM5JGWwUNoOcxHeivyPV9qfH+Q7WumHQN/x634WNOz9vCAptWfZmDcKVLL5vWq3iqprveOvw==,iv:DZgCvg+acoa5KeNkOOHHlHya81bXkr597jME8DhNm+M=,tag:HVLgJ0j/spOSnGKRBhjzJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMFJuTDNOMHpqWGg0dGho
            bmxYT25jQzJZM0crdFJMVE5RUUhOaW41T1E4CkFHNVRHYW95cTVyOXkwR3JRRFNV
            VDI2c09ISVp0ZC9iT3IyajAyMjRGS3MKLS0tIERLSGVCd1F4bm1QUk5uWDR3WnFV
            UXZ2RUpDOEozY0didlJucEJNUTNJSmcKlaa6MYkV5u8eXPWCT/LXHibFkjk3j6ZH
            fNqNrldj10+NJFXW4NYxPbwQKXrMr2s3yz5q+WyTyedy0s0zzp+elA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T08:57:15Z"
    mac: ENC[AES256_GCM,data:EkyaN0uu9/xVw+SVgQ7uxPwl+8e2PHnjKh9OlOJdLc7tyilOxsGrtzTCsIJ7Qn8/oOk4/qvQSIPXpLHHWDry7eb8EQDbcS+wEjY0m0aC+BIhb6WpWoZG0skgkx0dVmR6jcPyTQfyN6htavlnxElqHXMnxk1VfArC/YSTL0C73fE=,iv:FvScVym7V3XoXwmQ1meDLnVBEuZdF2t+q2vmHvClckA=,tag:x3OWbs4RRMVR1VVBh8iWOw==,type:str]
    version: 3.13.3
