apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:xseN4WKpvQisZ3TURa5sHkNZbSNDOf8Fnq+WXhWuxvGjRkkUVsTAiIw3xhHqbt305wQnh0TqnxZ6KpXPqu1SZ1kZZfCYV4VhiU60JUeD6g==,iv:iV0Ey8ho/9g/4HJRMKuX5hqnCMrZ3JxUwNDQ0hGsSLQ=,tag:aOudZEUkBlNx6HhTQAbEtw==,type:comment]
    #ENC[AES256_GCM,data:PWgCtE8riwU5Zw5lMlaReIQ0sc8Mz7g=,iv:ZhQ/8S2IcafzXqz2JMZdI5MELoLjWkJCM4cB6dIlsbc=,tag:1Gje9od/hb7o6tgTPa1+3g==,type:comment]
    encryption-key: ENC[AES256_GCM,data:RmwnN9tN3pd9Zl1wIT5QcJY0xR1bFucxoBIR+eTadVRaovOO7UEJl9i0ZL6C6ywOLsGe/zkiAKxm5mgcZ/KNTA==,iv:tR1AzXYSzGl4un3caNcr4kec+MR4Revqyfvvn9oCbWc=,tag:MtCZvprA6rUrK5wmR893YA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbmltdklGcFZrWUtlNi9S
            b1RyZVFobkRmQkVtaVM3N0RIUEcvMk1LSkNjClRCVWg4cktOZm1Za1BrbkJLdWgz
            RlFMSkUwTFI2UWlaLzdERkJQMEpyRDAKLS0tIG0wc3NVSGNOWjhBY3FHajFFOTN3
            bHVhTVdBbFBtUE5zc3NDeXRaWVF6eEkKrUMSAtpQPdMeJVv2Qu2a4IP3paQo9gMr
            jis4N4nmDkAVS7W4XWFpsCnrR3P35gesX4KXuCrrgMcVaGscmtFnVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T14:28:37Z"
    mac: ENC[AES256_GCM,data:r3CkST3ZPaX2wF5fbofhnYmIiY9lz0PU6N3gmZC4XaS//ucyaxyJ4+ZIlliXa9zohK4i2BHG01ekUU+19ejl+bWyEMJDb7kFF1izdld2DswzIfcatvM1D7OvBokZJpcxDhoCHbHCVQHbtDiRXGSz9AQK0eHCpVhvJ6ZjIi8kDe4=,iv:6TD43aL7KMcOEFpqpLUyRqxObfHPodSbb21AWv2Sl6c=,tag:hOX0GU5a+cjsa5GBlinr9A==,type:str]
    version: 3.13.3
