apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: default
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:AAMFKF4=,iv:IGKIWqBb1ML5MssOktbC7FLx8MMJ5QuqHP/Ph4NZwxE=,tag:xZqXPfuP3UbxICCOEY7qdw==,type:str]
    admin-password: ENC[AES256_GCM,data:pCFUnz3dJU+/VD5Fr/1wSfDjfZfE788T,iv:BTFl1Tqy0M2wHiIdBotE7ZAn9CCZCrHVECPhqyp7SGQ=,tag:UAEn/0jt4pPshG0xBAbNDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSS9wL0t5b0crSVdGT25E
            VFdGK09UWDBHT3NSZjNHeU1pMTE5cFFYcGwwCjZKSlJ6N3RJbDBZRlBDd2NyU0Rn
            Ny9pQ21Kc2VVQjhySkRWVmRZRHk3VjQKLS0tIHpqeng1QmR3VjJZaVB0b3VQUzEw
            SnN2UzdoUDNud082RElBT2N6Tzg3eTgK0ezMPNv5s5IbgEfk1M5aUKrYeJWVd7Cq
            /rgFID5g9Gp4y3jzvKFoViv9ojZlMJ706LnpD3KQope+eX/3gZrfZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T14:01:14Z"
    mac: ENC[AES256_GCM,data:BLvXCrleSHQiHz9LRoZIjrH3HGFJz5Yo2tJpZTmJd6iZpT5+oGqSVtOVxsF3F/zbzrnz8fmMg0XDb9k3d0yJwv46GB9FW5Rh+XFpmQecMki57NM5Q5JjXrQNh4Hx8PtWAsMpIerhWW9ov9gXlBxRdPaUeaT+JhKa2PGIMKPg2h0=,iv:zfFB8FV9GrIZar30lWIFtZDX93akIfTlUYrnGAHSH7o=,tag:Z8/UoR9QNOMsisabm0cvyQ==,type:str]
    version: 3.13.3
