apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: default
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:aEV4Zqc=,iv:F9Lh579scTGMOtVDGzEAMt9/djpuydR0PmRvZlhRy0E=,tag:GsORqGbCQljmJ20nJ1eF2w==,type:str]
    admin-password: ENC[AES256_GCM,data:0DEdYCQrXsuMPX7q1xfJ/v3rtYlHbXpE,iv:1soHK6HMxcSiz4nMqHJOmnJO1XkupvawI5tgKOrxhNI=,tag:KQdz6RFVYf/ifr4nX9ZrZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaTdNVWtUL1c5aEJ3cDha
            RjdjSzExSTZkemdUMzYyU2RGamhhNXlINHlBCjNNK3IxSS91SFRsYzRYUC9aVS9P
            UTVLb3BjTVVVdlBka0xXS2VnektmNzAKLS0tIDJSYnV1RUhSenRQNDBZMStWeFRn
            bituTTJxbC9Oa1lIYk5abzYrYmIveWsKGGbYFbgJsmkeymypfJN4yk9kJS65jGXi
            Kz0nocIwiKft5ZZN20C7uKltfj0tdooq7fY2cC9kpmmJy+Ok3urRsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T14:28:37Z"
    mac: ENC[AES256_GCM,data:+nAYY48AtPOnaA5HQnyW1G3gJ/kI6yo1zljj7EL35n3hvuHzfpod5RlhaJkzWcxz2YbS7mBUmed0aIc47qgd0t7UsaNF48BFITOAwD2Zo3CFKAv2P93P1No1ulPgNkNjJqgWtelncTeDsBwqKnCkLpJ6+YhHpptiUkEleVlkaew=,iv:bKNl1KV8kgSsVjQMXE2DFs1BWW9MS553En+l4II2mlc=,tag:9zQZV10o+3Y6O2gQ1xKUiA==,type:str]
    version: 3.13.3
