apiVersion: v1
kind: Secret
metadata:
    name: tg-secret
    namespace: default
type: Opaque
stringData:
    bot_token: ENC[AES256_GCM,data:8LHus16CaFFDHgyPyP5FDHFqqZF6S0VSUNstpRjXCzOxzhuEWYJEKq0VRjsN5w==,iv:adpsPVts4yRr6/rIfkUB9NaGOxEC80x9TykpA2urqlI=,tag:WEfHOOhWOewngf+kuaHgcw==,type:str]
    chat_id: ENC[AES256_GCM,data:4ICj0i9+q/bp,iv:gdXJ4OirldsYniMYn9UAxgd/XJ8Ci8e68Nv9IqEFs04=,tag:Me/B95kjGeqSZNIlStljIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VUNiQ0ZmMHZKNjRyMUdj
            YjV0MVphQ0ZCYUpnNUhBZG1xU2tFRUNFU25zClo5YWp3M09wSEI0enlhMGtlQ1dO
            VzdEekVvaUY5Y3NiOEk0cXlqTGRRd28KLS0tIGlMN1piVTNybWpuT3RnM0hNa2lN
            K0tmTEViWTlQcm5kTnZIK0lsaWFJWjgKeXRqRsjW4N/dSjhep7Xt6z5O4cjrdkjs
            RDFm+Slp8UErAPbxaYrR9aFrtcWbsnTmzBCpXWzLXTWBvaEHtJNuvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T11:31:18Z"
    mac: ENC[AES256_GCM,data:4hjr/3qACuKEmISJArYdhWfwaSUp+xantt0AWjUmkV8Ad5i7+CSBDXfC0aPHme+p0Pg6M5xcnDqymlLYoD15Gd9q3n9RLYlqZHHdvPOJHJFoUwvvClCNAfgke5Fi961cN0OCbtF8AZOpnuqn16V5IPbPu5751NXrsMkzCVzbxcg=,iv:s7O4UAMiJLPab4Q5To7S13QD9p+u3xh8H/llp978HgE=,tag:n7GJog8UumIerB5twd2GSQ==,type:str]
    version: 3.13.3
