apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: default
spec:
  schedule: "0 0 * * *" # daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres:alpine
            imagePullPolicy: IfNotPresent
            command: |
              export PGPASSWORD=${POSTGRES_PASSWORD}
              pg_dump -h postgres -U postgres -p 5432 -F c -b -v -f n8n.backup n8n
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: admin-password
          restartPolicy: OnFailure

# pg_restore -h localhost -p 5432 -U mlops -d <target_db> -v filename.backup