apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:lbxD6J4salVCsMO6Y6380Tieifn3Dfb7T2GKb7YRTJU6mNmCtU4Ljo0oVITthgLsgrX/VFkQj2ABMZNFrXxTKVXwRorykGkx+IB899icVFGSC60Uuta8Zg==,iv:3/mNo6NzYN9SY5MMy9kGPTCjGaXrezR9e9RN7L4bNT4=,tag:9A+LerNZcFTMaOeowiIWgw==,type:comment]
    username: ENC[AES256_GCM,data:RnIVvQ==,iv:VSzn/ov7hJXseBecVcI7YyTzfkLAE4W4U+842Z/U7+0=,tag:ZIpWC0/+KasaRo3Rr4bXwg==,type:str]
    #ENC[AES256_GCM,data:s0nRb/dVdBxegmSwaF3qI9FaBPlI9GfU1CqZAGnm32+LEW6UqqIAWNJQtpuiJ885++upr1hdysUin7aOYDw6HnakZGGOxNpnpe40mGh2xhhy0rIm2Mo=,iv:74EGnay8HX7+zqJnhs0DdVybiWHFurfnQ41cCA8MzGI=,tag:n9DBANYgtTMCRqBH0b3yuA==,type:comment]
    #ENC[AES256_GCM,data:rWruBlNDH7OIQyz9W4FfYryrEKEYZ9iWoS4=,iv:wRl/JuPL6YXwoE9rg025qRBovZMglYT1lQghRt3/YOk=,tag:ZiDoqnBt0NGeZWH1KokCrg==,type:comment]
    postgres-password: ENC[AES256_GCM,data:ZKgl7pcA5tIuUu+GmrTd5jxQ2tGRPfT6,iv:BZfuqt18xjPpagukn6TF52pcAJVcnKDxb+Uy26qDA3I=,tag:uRHzlal+qkaBFhP2SBtIVA==,type:str]
    admin-password: ENC[AES256_GCM,data:M8KIo3y7Qz7jjmHbb00DwJNXdffhz8Db,iv:qI4lQI3uW10bZe6hjoVKQYk0OtaZnhaJ3q+fcQSpLBI=,tag:8vN4vsyZxjCJwXJD7gtzQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZTl5R3J1K2FzVUw3UVNY
            Y1FhM1hMT09CZkNZSXhLWXhjTkNPeGlVcjNBCi8zTTUvZmdhem1zVU5TVW5wbFVZ
            NnRCcVJpV2p5ZmFNNHlGc1BTSXJaQ0EKLS0tIFRZTTFCUzRieUU0cGxDTnhaaWZq
            d01iTWZiV0dVQlFzQ21wMTlsT1dRSzAKPa/aJRQvCIUsliKCElJ92qYid8NiU2Fr
            h6WCFFaqduvaSerWKAEqi4BhD+BOScHrfwixZRHgOFukOVe6lkpLJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T07:32:42Z"
    mac: ENC[AES256_GCM,data:YwLpcIXk32UNfwohhIJrt9i6HWUYPuiflDTcuyupAcy1GMQDt8hqG46rPdd5ASA+zH892K5aab3KIiD7YFjaurHHvL/bc+RrNXgDZG0qTrxn6W+at0pEwaV1x30cw6/Lxmkr9sFvF7Zb11P85lzw2R5Kz6TZ3txebPXLRxWjSuE=,iv:MZ6WuxVAm0O0AnWJVMvhPlCH4acDbPt2A2Z4udhEYDY=,tag:Pns1Hrj2eWStRtXRPu77kQ==,type:str]
    version: 3.13.3
