apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:JbPEsFoL4xcZ1TBB651JLPKK+plk5jJ5Dizn9UnXDAUo/ySJP4ygr+0gcMIzk3cyVPf6EzI38NBXauFot7Rik2r4xgVAxOCyOWIdM3AbnsqU/0hhWLA=,iv:HdY8KMz+wYFVHm/82BktfNVzuup4NcNMlU6APNUnlXc=,tag:5ZxJ5g1AT762QMgdJz/Yig==,type:comment]
    #ENC[AES256_GCM,data:D5+YrNe4f5zwO+adknOgoq/atT4Ig2OO2H0=,iv:bFrAAGv1g11yp4SC5JC2W8bwoTpUjZ/NHy6DgawlnAQ=,tag:VSUFWgRkFEs3+ECay6RJUQ==,type:comment]
    postgres-password: ENC[AES256_GCM,data:isqlJiTJ3EIgfSTxNVH6rYkMiHacgRLf,iv:vLqUJoTxRmB2Uhjf+5HTgxbzolMYirRP3B5MhGWpe1A=,tag:puDYK7XTy7H4G2P1NBgcOg==,type:str]
    admin-password: ENC[AES256_GCM,data:9JRGGTfR9AFkiBDEKed/DPgKfaMOoTuj,iv:8nj6Z0MzWqDTzNsJaRkCDLuNcVUwGyMJ0wgktNFMO1g=,tag:5SLpFZF5axWAkAihyR5tLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYkRId0ovcWV4Y3hRYnBH
            VXY4dDJnNzB6L1R0b2FnQjNlYVovK083cTNBCmh6VmRER0tCQ1dnaVlPUzBLY1VI
            TUNleGYrYXJOYjQ1alNpNUJvZEVTQTgKLS0tIHRoOWVXZitwVVFSYm1hZXZ1ejRv
            ZE1GNEJvWVNYY0czM0p5SFlYU1VjZG8Ke3Jc3J1OIr2P+5iK0nA4Fzqhr3VrovfM
            O933RSKh1ftdh98dHA37SV35KQ1WazquRV5qZpDB1j4wfP+hntUpAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T06:45:43Z"
    mac: ENC[AES256_GCM,data:QvDTuClxOxr5iCjiasXx32gBQ1wNvKlm/2Y6X5t9yfpFw3rGQo0/TYgvkWWrKbZx2Mu+Bn2acOpIgL+Q/Ysn4sAj41wBBUA0TxQ1WZFjJfZ+xPnjL/e1Q2hjdhnxR3xKbkxffsQm5Tts62BcomB3ioq3tUnbcUCvQ6qRR8g8Xb8=,iv:m3Qu21QzJZ0IiJER1loDwEIYcYZhVe8A7WMqOGOUGDs=,tag:fNmVPkD1lGsUbNhb6Vmo8g==,type:str]
    version: 3.13.3
