apiVersion: v1
kind: Secret
metadata:
    name: dagu-basic-auth
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ltiARlg=,iv:velzTCsRgxfrGgdrTNrQsB/+JuHkuhtIC7g6eswbrGk=,tag:huQqIHBMXggnQhtr4d5e9w==,type:str]
    password: ENC[AES256_GCM,data:ROvDMFFMcR+Pi92ahl49UdeW7SpQtHDV,iv:YyEpg9yFimgeew7AbseUWyEG+0OTWJ2nQAqpsIJchUo=,tag:m4N2PkBtyaA19VjZoNEflg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNnVKdmJnTW50MklRVUN6
            Z21adStKSnhzL05TZ0RXQ003YktHSTJqazI4CmxmcXNkSHRmSmVqYWZzd3g0MDFM
            MXBvV1pjNmIrNmE5eWpYcS92dm5Rc1EKLS0tIGVDTDM3b3hLNmYvUmRWYXlRY21s
            czViajR2MzJLZ09MdzhZakRTVUNXa28KJt7hW0a6U/yWzfIAIzqrislbmie8B+ea
            mkxxX9ECfMxAJvs9p4Te6Rs/vOV2/Io3I1Dtvc1LJAn5W+aRV7+0XQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T08:11:58Z"
    mac: ENC[AES256_GCM,data:JcHo8Ga7yItyKfbkv3rDQPjyL4PEH4XGhza8nGyxiIhMH++lQ6Jemu9RcW4LvL5i2oowl4KbN3vS5mFEvHoZNymPk10mwgTRgR89pAxO6G2w4EQYze3wGo5IQcvXK6x6gOWvSKkkQlJw0uspRH8t3n/ktnvZPZ3BAqW79hUJG1I=,iv:PsC4HzV9LvQNLA56vzCADsExCVGM/zR2jb/CwxGxxVI=,tag:eHl5p+OFGo4HKLZo9J3F+g==,type:str]
    version: 3.13.3
