apiVersion: v1
kind: Secret
metadata:
    name: dagu-basic-auth
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WEIhTbg=,iv:8v28SgmJTZlj1/VWgqkNwMGYskz9QYHLQJ6UIUPA7l0=,tag:SArXvzSOVhcpQUoY2hVTYw==,type:str]
    password: ENC[AES256_GCM,data:8WKyCYolpgjUG6dKl2wy+lzb/8/ymX7J,iv:ab0kzqlOXxS2eLIMHPFzvjPFZH4oUT3B6oYx4jrCxT4=,tag:Tg9YfcrbAv0VsEGQ8u8fOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U1hYM3dZT1h2c2RuVXZD
            RzlqU0dYdEE3bHZQblRKdTU3M0lFd3U2d3prCjY3TkJNb2xkelZyOE5XY2pwUUdu
            RFhUOHdmWTQraFI3aCt2RVIwN1FneWMKLS0tIEVHcWlVVkFuTWoyTHQrV21LTWYy
            aXBOSHVOdU9uM2t6RCtGVjFtV1JPWFEKlkocX7ZY9gBtrv7Y/Abkh6Sv8Y6NCK1a
            Y6b8F8taTULwjS8KBUwsGhEbj4ihscN1DCKWUyUA8xlFIptAv6mW0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T14:28:37Z"
    mac: ENC[AES256_GCM,data:JQjXanxyaU8P97eyLoWKmk/uoJ7QKhx9DUeiBYIf6c5Gexs3EBa13m5hDLKnM0M2CnPYIBgW1RwJgvsqs0MCZ1MPxEiwYpTeZh8JzzKWac7STMsHTR2d3uhhr8DehJ3aOcrbSWcP2RGSFMaVEqxDvKH9s172cmWD/+1xeH+SUJg=,iv:Y26tjhgfBZJdWY2zu0bC2fr1bxmXiezDHwyhcOFVcJI=,tag:myYCfOd/tsQ05O/Cp5N3mA==,type:str]
    version: 3.13.3
