apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: default
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Szkt++G3WzmurShesawn+yXkTCgcdnXhcUy3I0x5qkcea9eZ7cBrjpp+vjU67iP9tuurgvw=,iv:dzcp8oY3SoqPT9i/uOzJK4S6hAtZzRMVqaYjfq+xTtM=,tag:rPh0t8el8B4lw91LhuqXbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT0hwWTdHL0dVbWc2d1Bs
            Y21YVUZIMFlZcHZxS3gyaWJRME5sSVVIVEg4CmNjNzZJQldVSWVWb3RYZG9HUzlo
            ZG5xZ2h4OXlQK3NEd1Q2c0lhYzJBaVUKLS0tICtHRHBUYktiRXFVQ2xNU0FjL1Nh
            M2ZPWlhNRUc4RmcwckduaGN0WUtKaU0K30REIo+AjGXr7RBngEhZSUA3objdsekk
            RhGy76LHJyk6CIbDEXsoyX0jEUx50JNBdihbHYdjzkRSrU145zXfuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9wcxcdm4tkjqd5daaal2kqxutmpu3nxq8zxlry5atjs82n8yvqsq9kga0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T16:24:35Z"
    mac: ENC[AES256_GCM,data:NKXtmOODNlMuorHylpGnJHejxxKm1AhC8UvOMizNGw4TgROmjHoqgbiyjAL1ddmFCHyda/Hcj68ADQxphcmDH/8NCLpGbjWlaOSF8dsF5gJqqEIzJCPQGC5qTeB95Dic7uTuD7sh21lBb69cFVySFy1YTRYmMraEMj4KbMHL6Jk=,iv:g7AcSq3gFUma2LzxkvTDEG1OLcdRGNk3jcS3Rzx7jX4=,tag:wEDJXv0Gyg7apZqj1zX38w==,type:str]
    version: 3.13.3
